CXXCBC-153: Added automatic inclusion of the Capella Root CA.
couchbaselabs/couchbase-cxx-client pull request #179
Opened 2022-04-07 19:13 UTC by brett19

2022-04-08 07:38 UTC, chvck commented
Have tested this with the PHP client and it looks good to me. An extra test from python could be good though, I'm making this up as I go along...

2022-04-11 16:35 UTC, avsej requested changes

2022-04-11 16:35 UTC, avsej commented on couchbase/capella_ca.hxx
> +                                   "-----END CERTIFICATE-----\n";
nitpick: can we expose static function here instead of the string? and put the string into object file? to avoid possible ODRs

2022-04-11 16:35 UTC, avsej commented on couchbase/cluster.hxx
> +                if (node.find("cloud.couchbase.com") != std::string::npos) {
I would prefer more strict check here. 

```c++
static std::string suffix = "cloud.couchbase.com"; 
if (auto pos = node.find(suffix); pos != std::string::npos && pos + suffix.size() == node.size()) {
```

https://godbolt.org/z/MMbn8z1ja

2022-04-11 16:59 UTC, avsej approved these changes

2022-04-11 17:30 UTC, merged