CXXCBC-510: Support binary objects in transactions
couchbaselabs/couchbase-cxx-client pull request #576
Opened 2024-06-05 06:56 UTC by avsej

2024-06-05 06:58 UTC, avsej commented
Several FIT tests still failing, in particular 
* ExtBinarySupportCleanupTest
* ExtBinarySupportTranscoderWritingTest

2024-06-06 05:39 UTC, avsej commented
Right now tests fail to compile, this is due to the main test coverage is done by FIT. I'm going to update unit tests tomorrow. But the implementation is complete now.

2024-06-11 01:15 UTC, brett19 requested changes
Tests should be fixed before merging.

2024-06-11 01:15 UTC, brett19 commented on .github/workflows/windows.yml
> +          # CB_CMAKE_BUILD_TYPE: Release
This doesn't seem related to ExtBinaryTransactions?

2024-06-11 21:01 UTC, brett19 approved these changes

2024-06-11 23:05 UTC, merged