CXXCBC-7: eventing functions management operations
couchbaselabs/couchbase-cxx-client pull request #95
Opened 2021-12-30 12:04 UTC by avsej

2022-01-03 15:46 UTC, avsej commented
test this please

2022-01-03 16:16 UTC, avsej commented
test this please

2022-01-03 18:25 UTC, avsej commented
test this please

2022-01-03 18:44 UTC, avsej commented
test this please

2022-01-03 19:11 UTC, avsej commented
test this please

2022-01-04 08:09 UTC, avsej commented
test this please

2022-01-04 09:25 UTC, avsej commented
test this please

2022-01-04 13:16 UTC, jrawsthorne requested changes
Looks good. Just found a few typos. It would be good if more of the function settings were tested to catch those typos but I can create a ticket for that

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/errors.hxx
> +                return "eventing_function_identical_keyspace";
```suggestion
                return "eventing_function_not_bootstrapped";
```

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_status.hxx
> +    std::optional<bool> redeploy_required{};
This is not in the rfc, should it be added?

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_function.hxx
> +    function_bucket_access access{ couchbase::operations::management::eventing::function_bucket_access::read_only };
Default is rw https://github.com/couchbase/eventing/blob/b35dfcc1239b619a764b33246ce488db51e4cd4d/parser/depcfg_schema.json#L51

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_function.hxx
> +enum class query_scan_consistency {
The rfc suggests this should use the same data structure as queries rather than defining a duplicate version.

2022-01-04 13:16 UTC, jrawsthorne commented on test/test_integration_management.cxx
> +              "data", { "default" }, couchbase::operations::management::eventing::function_bucket_access::read_write });
```suggestion
              "data", { integration.ctx.bucket }, couchbase::operations::management::eventing::function_bucket_access::read_write });
```

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_upsert_function.cxx
> +        settings["lcb_lcb_inst_capacity"] = function.settings.lcb_inst_capacity.value();
```suggestion
        settings["lcb_inst_capacity"] = function.settings.lcb_inst_capacity.value();
```

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_upsert_function.cxx
> +        settings["lcb_lcb_retry_count"] = function.settings.lcb_retry_count.value();
```suggestion
        settings["lcb_retry_count"] = function.settings.lcb_retry_count.value();
```

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_upsert_function.cxx
> +        settings["lcb_num_timer_partitions"] = function.settings.num_timer_partitions.value();
```suggestion
        settings["num_timer_partitions"] = function.settings.num_timer_partitions.value();
```

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_upsert_function.cxx
> +        settings["enable_app_log_rotation"] = function.settings.enable_app_log_rotation.value();
```suggestion
        settings["enable_applog_rotation"] = function.settings.enable_app_log_rotation.value();
```

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_function_json.hxx
> +        result.function_instance_id = v.template optional<std::string>("functional_instance_id");
```suggestion
        result.function_instance_id = v.template optional<std::string>("function_instance_id");
```

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_function_json.hxx
> +                if (language_compatibility_string == "6.6.0") {
```suggestion
                if (language_compatibility_string == "6.0.0") {
```

2022-01-04 13:16 UTC, jrawsthorne commented on couchbase/operations/management/eventing_function_json.hxx
> +            if (const auto* query_consistency = settings->find("query_consistency");
```suggestion
            if (const auto* query_consistency = settings->find("n1ql_consistency");
```

2022-01-04 14:57 UTC, avsej commented on couchbase/operations/management/eventing_function.hxx
> +enum class query_scan_consistency {
it will be refactored later, right now query scan_consistency is part of the query request namespace.

2022-01-04 15:00 UTC, avsej commented on couchbase/operations/management/eventing_status.hxx
> +    std::optional<bool> redeploy_required{};
I will remove it, right.

2022-01-04 15:09 UTC, jrawsthorne commented on couchbase/operations/management/eventing_function_json.hxx
> +                    language_compatibility_string == "6.6.0") {
This got overwritten with the force push
```suggestion
                    language_compatibility_string == "6.0.0") {
```

2022-01-04 17:22 UTC, jrawsthorne approved these changes

2022-01-04 22:18 UTC, merged